# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

make_grid <- function(x[], y[], *grid_size, *pixels, grid[]) {
    invisible(.Call(`_rSPACE_make_grid`, x[], y[], *grid_size, *pixels, grid[]))
}

sample_ind <- function(x[], y[], *N, *buffer, use[], *maxid, new_order[]) {
    invisible(.Call(`_rSPACE_sample_ind`, x[], y[], *N, *buffer, use[], *maxid, new_order[]))
}

use_surface <- function(x_wolv[], y_wolv[], *N_wolv, x[], y[], snow[], *pixels, *sd_x, *sd_y, *trunc_cutoff) {
    invisible(.Call(`_rSPACE_use_surface`, x_wolv[], y_wolv[], *N_wolv, x[], y[], snow[], *pixels, *sd_x, *sd_y, *trunc_cutoff))
}

calc_prob <- function(use[], grid[], detection[], *detectionP, *pixels, *max_grid, test[]) {
    invisible(.Call(`_rSPACE_calc_prob`, use[], grid[], detection[], *detectionP, *pixels, *max_grid, test[]))
}

